name: Pull Request CI (Docker Compose)

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (recommended for latest Docker Compose)
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose services
        run: docker compose -f local.yml build

      - name: Start Docker Compose stack
        run: docker compose -f local.yml up -d

      - name: Run black
        run: docker compose -f local.yml exec -T api black --check .

      - name: Run isort
        run: docker compose -f local.yml exec -T api isort --check-only .

      - name: Run flake8
        run: docker compose -f local.yml exec -T api flake8 .

      - name: Run pytest
        run: docker compose -f local.yml exec -T api pytest

      - name: Stop Docker Compose stack
        if: always()
        run: docker compose -f local.yml down --remove-orphans
