name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DO Droplet via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH }}
          environment: "Digital Ocean CI/CD"
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            if [ ! -d /app/.git ]; then
              rm -rf /app
              git clone git@github.com:vitorguima/mentoreed.git /app
              cd /app/mentoreed
            else
              cd /app/mentoreed
              git pull origin main
            fi

            docker compose -f production.yml up -d --build --remove-orphans
            docker compose -f production.yml exec -T api python manage.py migrate --noinput
            docker compose -f production
